language: node_js
node_js:
  - "node"
install:
  - npm install -g codecov istanbul
script:
  - istanbul cover test/test-index.js --reporter lcovonly -- -R spec
  - codecov
after_success:
  - bash < (curl -s https://codecov.io/bash)